env:
  global:
    - LANG:tr_TR.UTF-8

language: php

php:
    - 7.3
    - 7.4

before_script:
    - phpenv rehash
    - composer install

script:
    - find ./src/ -name "CommandLoader.php" -exec php -l {} \;
    - find ./src/database/ -name "Database.php" -exec php -l {} \;
    - find ./src/commands/ -name "*.php" -exec php -l {} \;
